spring.application.name=devops-app
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/devopsdb}
spring.datasource.username=${DB_USERNAME:devopsuser}
spring.datasource.password=${DB_PASSWORD:devopspassword}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true